services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    tty: true
    ports:
      - 8080:8080
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend/:/usr/src/web
    tty: true
    ports:
      - 5173:5173
  db:
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: ht
      POSTGRES_PASSWORD: psht
      POSTGRES_DB: myapp-db
    # volumes:
    #   - db-store:/var/lib/postgresql/data
